<?php
	session_start();
	
	if (!isset($_SESSION["cart"])) {
		$_SESSION["cart"] = array();
	}
	
	$items = array(
		"Chair" => array("24.99", "A beautiful chair full of wonders!", "A chair is a piece of furniture with a raised surface supported by legs, commonly used to seat a single person. Chairs are supported most often by four legs and have a back; however, a chair can have three legs or can have a different shape. Chairs are made of a wide variety of materials, ranging from wood to metal to synthetic material (e.g. plastic), and they may be padded or upholstered in various colors and fabrics, either just on the seat (as with some dining room chairs) or on the entire chair. Chairs are used in a number of rooms in homes (e.g. in living rooms, dining rooms, and dens), in schools and offices (with desks), and in various other workplaces."),
		"Table" => array("159.99", "Need a place to eat on and set your stuff on? Here it is, the table!", "A table is an item of furniture with a flat top and one or more legs, used as a surface for working at, eating from or on which to place things. Some common types of table are the dining room table, which is used for seated persons to eat meals; the coffee table, which is a low table used in living rooms to display items or serve refreshments; and the bedside table, which is used to place an alarm clock and a lamp. There are also a range of specialized types of tables, such as drafting tables, used for doing architectural drawings, and sewing tables."),
		"Couch" => array("899.99", "A place to rest your head, lazy around, and play those games!", "A couch (U.S. English, British English), also known as a sofa, settee (British English), or chesterfield (Canadian English and British English) is a piece of furniture for seating three or more people in the form of a bench, with or without armrests, that is partially or entirely upholstered, and often fitted with springs and tailored cushions. Although a couch is used primarily for seating, it may be used for sleeping."),
		"Dresser" => array("199.99", "Storing clothes? This is the thing for you!", "A chest of drawers, also called (especially in North American English) a bureau, is a type of cabinet (a piece of furniture) that has multiple parallel, horizontal drawers usually stacked one above another. In American English a dresser is a piece of furniture, usually waist high, that has drawers and normally room for a mirror. In British English a dresser or a Welsh dresser has shelves in the upper section for storing or displaying tableware."),
		"Bed" => array("699.99", "Who needs to sleep? But if you do, here you go.", "A bed is a piece of furniture which is used as a place to sleep or relax. Most modern beds consist of a soft, cushioned mattress on a bed frame, the mattress resting either on a solid base, often wood slats, or a sprung base. Many beds include a box spring inner-sprung base, which is a large mattress-sized box containing wood and springs that provide additional support and suspension for the mattress. Beds are available in many sizes, ranging from infant-sized bassinets and cribs, to small beds for a single child or adult, to large queen and king-size beds designed for two adults")
	);
?>